### PR TITLE
feat(python2and3): update cobra to support both python versions 2 and 3

### LINKED ISSUE #21: Device package upload does not work
A change was made prior to cobra being pushed to github that breaks device package upload.  Specifically:

https://github.com/datacenter/cobra/blob/master/cobra/mit/access.py#L85

```
def commit(self, configObject):
    if configObject.getRootMo() is None:
        raise CommitError(0, "No mos in config request")
    return self._accessImpl.post(configObject)
```

Not all classes that derive from `AbstractRequest` will be doing HTTP POSTs with the `MoDirectory.commit()` method will actually be POSTING MO's.  For example `cobra.mit.services. UploadPackage` uses the commit method but doesn't try to commit actual MOs.

### PR DESCRIPTION
**Pull request by mtimm**
This depends on the future module. There are still outstanding issues that I know of:
1. From time to time doing a full subtree query of topSystem results in a ValueError when modifying a child Mo.
   For my testbed it is always when adding a key to eqptcap.SfpMfgDef for the naming value.
2. shippable.yml needs to be updated to run tests on python3. I'll be adding that next.

Working on #20 and closes #21

### CODE REVIEW

**Comment by mtimm** [comment]
Here is more info on the intermittent failures when doing full subtree queries on topSystem.  The stacktrace of the failure is:

```
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/mit/access.py:65: in query
    return self._accessImpl.get(queryObject)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/rest/accessimpl.py:172: in get
    return self.__parseResponse(rsp)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/rest/accessimpl.py:198: in __parseResponse
return fromXMLStr(rsp.text)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/codec/xmlcodec.py:41: in fromXMLStr
    return _fromXMLRootNode(xmlRootNode)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/codec/xmlcodec.py:34: in _fromXMLRootNode
    mo = _createMo(moNode, None)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/codec/xmlcodec.py:75: in _createMo
    _createMo(childNode, mo)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/codec/xmlcodec.py:75: in _createMo
    _createMo(childNode, mo)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/codec/xmlcodec.py:75: in _createMo
    _createMo(childNode, mo)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/codec/xmlcodec.py:71: in _createMo
    mo = pyClass(parentMoOrDn, *namingVals, markDirty=False, **moProps)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acimodel-1.1_0.653-py2.7.egg/cobra/model/eqptcap.py:1158: in __init__
Mo.__init__(self, parentMoOrDn, markDirty, *namingVals,  **creationProps)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/mit/mo.py:75: in __init__
    **creationProps)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/base/moimpl.py:247: in __init__
    self.__parentMo.__modifyChild(self, attach=True)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/base/moimpl.py:307: in __modifyChild
    childContainer[namingVals[0]] = childMo
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/base/moimpl.py:106: in __setitem__
    self._checkKey(key, value)
/Users/mtimm/.virtualenvs/python3/lib/python3.4/site-packages/acicobra-0.1-py3.4.egg/cobra/internal/base/moimpl.py:125: ValueError
                raise ValueError('"%s" is bad key for "%s"' %
>                                (str(key), meta.className))
E               ValueError: "md5Xcvr50" is bad key for "cobra.model.eqptcap.MfgDef"
```

The failure is here:

```
self = <cobra.internal.base.moimpl.BaseMo._ChildContainer._ClassContainer object at 0x125a07588>, key = 'md5Xcvr50', mo = <cobra.model.eqptcap.SfpMfgDef object at 0x125a07240>

    def _checkKey(self, key, mo):
        meta = self._childClass.meta
        numNamingProps = len(meta.namingProps)
        namingVals = []
        if numNamingProps == 0:
            if key is not None:
                raise ValueError('"%s" is bad key for "%s"' %
>                                (str(key), meta.className))
E               ValueError: "md5Xcvr50" is bad key for "cobra.model.eqptcap.MfgDef"
```

One odd thing I don't understand is that this **ValueError** is printing `meta.className` which is based on `self._childClass.meta`, **eqptcapMfgDef** has no naming values, so not having a key here would be correct for that class, however this key should be for **eqptcap.SfpMfgDef** which is what the mo is that was passed into this code.  I'm just not sure why we are checking for a naming property for the child meta and pass in the mo as well.

@rchamarthy can you help me track this down?  You are probably most familiar with this code.  Thanks.

**Comment by mtimm** [comment]
Root cause for the ValueError mentioned in this pull request:

We have two sibling Mo's with nearly identical rn prefixes (eqptcapMfgDef with a rn prefix of _mfg_ and eqptcapSfpMfgDef with a rn prefix of _mfg-_ and one of the Mo's has naming values and the other does not.  Depending on the order in which class containers are returned in `BaseMo._getChildContainer()` we may get the wrong Mo class container.  The reason for this is that `BaseMo._getChildContainer()` strips off the trailing hyphen if it exists and searches for the class container based on just mfg.

We need a way to find class containers based on the full rn prefix without stripping it and still allow the behavior of finding the class container in a situation where a child is referenced like an attribute, as in: fvTenant.BD['default'].

**Comment by rchamarthy** [comment]
I am good with this. Please merge it.

**Comment by mtimm** [comment]
Thanks Ravi, I will merge.  I have some tests for mit/request.py coming.  Just very basic unit tests to verify that when we set things like properties what we get back from them is what we expect.  I'll cover that with a different PR.

**Pull request merged**
